name: changelog_workflow
on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: joshlynchONS/auto-generate-changelog@master
      with:
        REPO_NAME: ''
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: 'CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'add:Added,fix:Fixed,depreciated:Depreciated,security:Security,removed:Removed feature,change:Changed,docs:Documentation'
