name: changelog_workflow
on:
  release:
    types: [created, edited]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: joshlynchONS/gov-changelog-action@template_issue
      with:
        REPO_NAME: ''
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PATH: 'CHANGELOG.md'
        UNRELEASED_COMMITS: 'true'
