name: Create new tag
on:
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: joshlynchONS/gov-changelog-action@update_release
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CREATE_TAG: 'true'
